language: go
go:
- 1.14.x
- master

addons:
  apt:
    packages:
      - libgl1-mesa-dev
      - xorg-dev

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
